name = "pluffa-cloudflare-worker-example"
type = "javascript"
zone_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-02-27"
compatibility_flags = [
  "streams_enable_constructors",
  "transformstream_enable_standard_constructor",
]

[build]
command = "yarn build"

[build.upload]
format = "service-worker"

[site]
bucket = "./build/client"
entry-point = "."
